name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - name: Set-up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Test the scraper
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
          yarn
          yarn test

      - name: Send stats to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Check version
        run: |
          export TAG=$(git describe --abbrev=0 --tags)
          export VERSION=$(node -p "require('./package').version")
          if [ "$TAG" != "$VERSION" ]; then
            exit 1
          fi

      - name: Build the package
        run: |
          yarn build

      - name: Upload package to the registry
        if: ${{ !env.ACT }}
        run: |
          yarn publish --non-interactive